"""Pydantic schemas package."""

from app.schemas.ai_classification import (
    AIClassificationCreate,
    AIClassificationDetailResponse,
    AIClassificationListResponse,
    AIClassificationResponse,
    AIClassificationUpdate,
    AIToolCapabilityCreate,
    AIToolCapabilityResponse,
    ClassifyVendorRequest,
    RiskMatrixEntry,
    RiskMatrixResponse,
    StackTypeDefinition,
    StackTypeListResponse,
)
from app.schemas.agent import (
    AgentBase,
    AgentConfigUpdate,
    AgentCreate,
    AgentListResponse,
    AgentResponse,
    AgentStats,
    AgentUpdate,
    LogListResponse,
    LogResponse,
    TaskCreate,
    TaskListResponse,
    TaskResponse,
)
from app.schemas.auth import (
    LoginResponse,
    MFAEnableResponse,
    MFAStatusResponse,
    MFAValidateRequest,
    MFAVerifyRequest,
    OrganizationBase,
    OrganizationResponse,
    PasswordChange,
    RegisterResponse,
    TokenRefresh,
    TokenResponse,
    UserBase,
    UserCreate,
    UserLogin,
    UserResponse,
    UserUpdate,
)
from app.schemas.chunk import (
    ChunkListResponse,
    ChunkResponse,
    SearchQuery,
    SearchResponse,
    SearchResultResponse,
)
from app.schemas.document import (
    DocumentBase,
    DocumentCreate,
    DocumentListResponse,
    DocumentResponse,
    DocumentUpdate,
)
from app.schemas.finding import (
    AnalysisRequest,
    AnalysisRunListResponse,
    AnalysisRunResponse,
    FindingListResponse,
    FindingResponse,
    FindingSummary,
    FindingUpdate,
)
from app.schemas.playbook import (
    ApprovalRequestCreate,
    ApprovalResponseData,
    ChecklistItem,
    PlaybookApprovalListResponse,
    PlaybookApprovalResponse,
    PlaybookCreate,
    PlaybookDetailResponse,
    PlaybookListResponse,
    PlaybookProgressCreate,
    PlaybookProgressListResponse,
    PlaybookProgressResponse,
    PlaybookResponse,
    PlaybookStepCreate,
    PlaybookStepResponse,
    PlaybookStepUpdate,
    PlaybookUpdate,
    Resource,
    StepCompletionData,
)
from app.schemas.query import (
    Citation,
    ConversationCreateRequest,
    ConversationListResponse,
    ConversationMessage,
    ConversationRequest,
    ConversationResponse,
    QueryHistoryListResponse,
    QueryHistoryResponse,
    QueryRequest,
    QueryResponse,
)
from app.schemas.remediation import (
    RemediationAuditLogResponse,
    RemediationCommentCreate,
    RemediationCommentResponse,
    RemediationDashboardStats,
    RemediationTaskCreate,
    RemediationTaskDetail,
    RemediationTaskListResponse,
    RemediationTaskResponse,
    RemediationTaskUpdate,
    RemediationTransition,
    SLAPolicyCreate,
    SLAPolicyResponse,
)
from app.schemas.vendor import (
    VendorBase,
    VendorCreate,
    VendorListResponse,
    VendorResponse,
    VendorUpdate,
)

__all__ = [
    # AI Classification
    "AIClassificationCreate",
    "AIClassificationDetailResponse",
    "AIClassificationListResponse",
    "AIClassificationResponse",
    "AIClassificationUpdate",
    "AIToolCapabilityCreate",
    "AIToolCapabilityResponse",
    "ClassifyVendorRequest",
    "RiskMatrixEntry",
    "RiskMatrixResponse",
    "StackTypeDefinition",
    "StackTypeListResponse",
    # Agents
    "AgentBase",
    "AgentConfigUpdate",
    "AgentCreate",
    "AgentListResponse",
    "AgentResponse",
    "AgentStats",
    "AgentUpdate",
    "LogListResponse",
    "LogResponse",
    "TaskCreate",
    "TaskListResponse",
    "TaskResponse",
    # Auth
    "UserBase",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "UserUpdate",
    "PasswordChange",
    "TokenResponse",
    "TokenRefresh",
    "OrganizationBase",
    "OrganizationResponse",
    "RegisterResponse",
    "MFAEnableResponse",
    "MFAVerifyRequest",
    "MFAValidateRequest",
    "MFAStatusResponse",
    "LoginResponse",
    # Vendor
    "VendorBase",
    "VendorCreate",
    "VendorUpdate",
    "VendorResponse",
    "VendorListResponse",
    # Document
    "DocumentBase",
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentResponse",
    "DocumentListResponse",
    # Chunk/Search
    "ChunkResponse",
    "ChunkListResponse",
    "SearchQuery",
    "SearchResultResponse",
    "SearchResponse",
    # Analysis/Findings
    "AnalysisRequest",
    "AnalysisRunResponse",
    "AnalysisRunListResponse",
    "FindingResponse",
    "FindingListResponse",
    "FindingUpdate",
    "FindingSummary",
    # Query
    "QueryRequest",
    "QueryResponse",
    "ConversationRequest",
    "ConversationResponse",
    "ConversationCreateRequest",
    "ConversationMessage",
    "QueryHistoryResponse",
    "QueryHistoryListResponse",
    "ConversationListResponse",
    "Citation",
    # Remediation
    "RemediationTaskCreate",
    "RemediationTaskUpdate",
    "RemediationTaskResponse",
    "RemediationTaskDetail",
    "RemediationTaskListResponse",
    "RemediationTransition",
    "RemediationCommentCreate",
    "RemediationCommentResponse",
    "RemediationAuditLogResponse",
    "RemediationDashboardStats",
    "SLAPolicyCreate",
    "SLAPolicyResponse",
    # Playbooks
    "ApprovalRequestCreate",
    "ApprovalResponseData",
    "ChecklistItem",
    "PlaybookApprovalListResponse",
    "PlaybookApprovalResponse",
    "PlaybookCreate",
    "PlaybookDetailResponse",
    "PlaybookListResponse",
    "PlaybookProgressCreate",
    "PlaybookProgressListResponse",
    "PlaybookProgressResponse",
    "PlaybookResponse",
    "PlaybookStepCreate",
    "PlaybookStepResponse",
    "PlaybookStepUpdate",
    "PlaybookUpdate",
    "Resource",
    "StepCompletionData",
]
